---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: deepshare2-sn0
  name: deepshare2-sn0
  namespace: ds-production
spec:
  replicas: 1
  selector:
    name: deepshare2-sn0
  template:
    metadata:
      labels:
        name: deepshare2-sn0
        app: deepshare2-snowflake
    spec:
      nodeSelector:
        env: ds-production
        snowflake: "true"
      containers:
      - image: r.fds.so:5000/deepshare-snowflake:20160505
        name: ds2snowflake
        command: ["/go/src/github.com/MISingularity/deepshare2/deepshare2d"]
        args:
        - -service-types
        - token
        - -http-listen
        - 0.0.0.0:16760
        - -nsq-url
        - nsqd.ds-production:4150
        - -data-center-id
        - "0"
        - -worker-id
        - "1"
        - -log-level
        - debug
        resources:
          requests:
            memory: "1024Mi"
            cpu: "900m"
          limits:
            memory: "1024Mi"
            cpu: "900m"
        ports:
        - containerPort: 16760
          name: ds2snowflake
          protocol: TCP
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: deepshare2-sn1
  name: deepshare2-sn1
  namespace: ds-production
spec:
  replicas: 1
  selector:
    name: deepshare2-sn1
  template:
    metadata:
      labels:
        name: deepshare2-sn1
        app: deepshare2-snowflake
    spec:
      nodeSelector:
        env: ds-production
        snowflake: "true"
      containers:
      - image: r.fds.so:5000/deepshare-snowflake:20160505
        name: ds2snowflake
        command: ["/go/src/github.com/MISingularity/deepshare2/deepshare2d"]
        args:
        - -service-types
        - token
        - -http-listen
        - 0.0.0.0:16760
        - -nsq-url
        - nsqd.ds-production:4150
        - -data-center-id
        - "0"
        - -worker-id
        - "2"
        - -log-level
        - debug
        resources:
          requests:
            memory: "1024Mi"
            cpu: "900m"
          limits:
            memory: "1024Mi"
            cpu: "900m"
        ports:
        - containerPort: 16760
          name: ds2snowflake
          protocol: TCP
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: deepshare2-sn2
  name: deepshare2-sn2
  namespace: ds-production
spec:
  replicas: 1
  selector:
    name: deepshare2-sn2
  template:
    metadata:
      labels:
        name: deepshare2-sn2
        app: deepshare2-snowflake
    spec:
      nodeSelector:
        env: ds-production
        snowflake: "true"
      containers:
      - image: r.fds.so:5000/deepshare-snowflake:20160505
        name: ds2snowflake
        command: ["/go/src/github.com/MISingularity/deepshare2/deepshare2d"]
        args:
        - -service-types
        - token
        - -http-listen
        - 0.0.0.0:16760
        - -nsq-url
        - nsqd.ds-production:4150
        - -data-center-id
        - "0"
        - -worker-id
        - "3"
        - -log-level
        - debug
        resources:
          requests:
            memory: "1024Mi"
            cpu: "900m"
          limits:
            memory: "1024Mi"
            cpu: "900m"
        ports:
        - containerPort: 16760
          name: ds2snowflake
          protocol: TCP
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: deepshare2-sn3
  name: deepshare2-sn3
  namespace: ds-production
spec:
  replicas: 1
  selector:
    name: deepshare2-sn3
  template:
    metadata:
      labels:
        name: deepshare2-sn3
        app: deepshare2-snowflake
    spec:
      nodeSelector:
        env: ds-production
        snowflake: "true"
      containers:
      - image: r.fds.so:5000/deepshare-snowflake:20160505
        name: ds2snowflake
        command: ["/go/src/github.com/MISingularity/deepshare2/deepshare2d"]
        args:
        - -service-types
        - token
        - -http-listen
        - 0.0.0.0:16760
        - -nsq-url
        - nsqd.ds-production:4150
        - -data-center-id
        - "0"
        - -worker-id
        - "4"
        - -log-level
        - debug
        resources:
          requests:
            memory: "1024Mi"
            cpu: "900m"
          limits:
            memory: "1024Mi"
            cpu: "900m"
        ports:
        - containerPort: 16760
          name: ds2snowflake
          protocol: TCP
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: deepshare2-sn4
  name: deepshare2-sn4
  namespace: ds-production
spec:
  replicas: 1
  selector:
    name: deepshare2-sn4
  template:
    metadata:
      labels:
        name: deepshare2-sn4
        app: deepshare2-snowflake
    spec:
      nodeSelector:
        env: ds-production
        snowflake: "true"
      containers:
      - image: r.fds.so:5000/deepshare-snowflake:20160505
        name: ds2snowflake
        command: ["/go/src/github.com/MISingularity/deepshare2/deepshare2d"]
        args:
        - -service-types
        - token
        - -http-listen
        - 0.0.0.0:16760
        - -nsq-url
        - nsqd.ds-production:4150
        - -data-center-id
        - "0"
        - -worker-id
        - "5"
        - -log-level
        - debug
        resources:
          requests:
            memory: "1024Mi"
            cpu: "900m"
          limits:
            memory: "1024Mi"
            cpu: "900m"
        ports:
        - containerPort: 16760
          name: ds2snowflake
          protocol: TCP
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: deepshare2-sn5
  name: deepshare2-sn5
  namespace: ds-production
spec:
  replicas: 1
  selector:
    name: deepshare2-sn5
  template:
    metadata:
      labels:
        name: deepshare2-sn5
        app: deepshare2-snowflake
    spec:
      nodeSelector:
        env: ds-production
        snowflake: "true"
      containers:
      - image: r.fds.so:5000/deepshare-snowflake:20160505
        name: ds2snowflake
        command: ["/go/src/github.com/MISingularity/deepshare2/deepshare2d"]
        args:
        - -service-types
        - token
        - -http-listen
        - 0.0.0.0:16760
        - -nsq-url
        - nsqd.ds-production:4150
        - -data-center-id
        - "0"
        - -worker-id
        - "6"
        - -log-level
        - debug
        resources:
          requests:
            memory: "1024Mi"
            cpu: "900m"
          limits:
            memory: "1024Mi"
            cpu: "900m"
        ports:
        - containerPort: 16760
          name: ds2snowflake
          protocol: TCP
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: deepshare2-sn6
  name: deepshare2-sn6
  namespace: ds-production
spec:
  replicas: 1
  selector:
    name: deepshare2-sn6
  template:
    metadata:
      labels:
        name: deepshare2-sn6
        app: deepshare2-snowflake
    spec:
      nodeSelector:
        env: ds-production
        snowflake: "true"
      containers:
      - image: r.fds.so:5000/deepshare-snowflake:20160505
        name: ds2snowflake
        command: ["/go/src/github.com/MISingularity/deepshare2/deepshare2d"]
        args:
        - -service-types
        - token
        - -http-listen
        - 0.0.0.0:16760
        - -nsq-url
        - nsqd.ds-production:4150
        - -data-center-id
        - "0"
        - -worker-id
        - "7"
        - -log-level
        - debug
        resources:
          requests:
            memory: "1024Mi"
            cpu: "900m"
          limits:
            memory: "1024Mi"
            cpu: "900m"
        ports:
        - containerPort: 16760
          name: ds2snowflake
          protocol: TCP
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: deepshare2-sn7
  name: deepshare2-sn7
  namespace: ds-production
spec:
  replicas: 1
  selector:
    name: deepshare2-sn7
  template:
    metadata:
      labels:
        name: deepshare2-sn7
        app: deepshare2-snowflake
    spec:
      nodeSelector:
        env: ds-production
        snowflake: "true"
      containers:
      - image: r.fds.so:5000/deepshare-snowflake:20160505
        name: ds2snowflake
        command: ["/go/src/github.com/MISingularity/deepshare2/deepshare2d"]
        args:
        - -service-types
        - token
        - -http-listen
        - 0.0.0.0:16760
        - -nsq-url
        - nsqd.ds-production:4150
        - -data-center-id
        - "0"
        - -worker-id
        - "8"
        - -log-level
        - debug
        resources:
          requests:
            memory: "1024Mi"
            cpu: "900m"
          limits:
            memory: "1024Mi"
            cpu: "900m"
        ports:
        - containerPort: 16760
          name: ds2snowflake
          protocol: TCP
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: deepshare2-sn8
  name: deepshare2-sn8
  namespace: ds-production
spec:
  replicas: 1
  selector:
    name: deepshare2-sn8
  template:
    metadata:
      labels:
        name: deepshare2-sn8
        app: deepshare2-snowflake
    spec:
      nodeSelector:
        env: ds-production
        snowflake: "true"
      containers:
      - image: r.fds.so:5000/deepshare-snowflake:20160505
        name: ds2snowflake
        command: ["/go/src/github.com/MISingularity/deepshare2/deepshare2d"]
        args:
        - -service-types
        - token
        - -http-listen
        - 0.0.0.0:16760
        - -nsq-url
        - nsqd.ds-production:4150
        - -data-center-id
        - "0"
        - -worker-id
        - "9"
        - -log-level
        - debug
        resources:
          requests:
            memory: "1024Mi"
            cpu: "900m"
          limits:
            memory: "1024Mi"
            cpu: "900m"
        ports:
        - containerPort: 16760
          name: ds2snowflake
          protocol: TCP
