apiVersion: v1
kind: Service
metadata:
  labels:
    name: nsqadmin
  name: nsqadmin
  namespace: ds-test
spec:
  ports:
  - name: "nsqadmin-tcp"
    port: 4170
    protocol: TCP
    targetPort: 4170
  - name: "nsqadmin-http"
    port: 4171
    protocol: TCP
    targetPort: 4171
    nodePort: 31171
  type: NodePort
  selector:
    app: nsqadmin
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: nsqadmin
  name: nsqadmin
  namespace: ds-test
spec:
  replicas: 1
  selector:
    name: nsqadmin
  template:
    metadata:
      labels:
        name: nsqadmin
        app: nsqadmin
    spec:
      nodeSelector:
        env: ds-test
      containers:
      - image: r.fds.so:5000/nsq:20151022
        name: nsqadmin
        command: ["/nsqadmin"]
        args: ["--lookupd-http-address=10.100.207.1:4161"]
        ports:
        - containerPort: 4170
          name: nsqadmin-tcp
          protocol: TCP
        - containerPort: 4171
          name: nsqadmin-http
          protocol: TCP
