apiVersion: v1
kind: Service
metadata:
  labels:
    name: nsqd
  name: nsqd
  namespace: db
spec:
  ports:
  - name: "nsqd-tcp"
    port: 4150
    protocol: TCP
    targetPort: 4150
  - name: "nsqd-http"
    port: 4151
    protocol: TCP
    targetPort: 4151
  selector:
    name: nsqd
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: nsqd
  name: nsqd
  namespace: db
spec:
  replicas: 1
  selector:
    name: nsqd
  template:
    metadata:
      labels:
        name: nsqd
    spec:
      nodeSelector:
        env: DB
      containers:
      - image: node-00:30500/nsq:20151022
        name: nsqd
        command: ["/nsqd"]
        args: ["--broadcast-address=nsqd.db","--lookupd-tcp-address=nsqlookupd:4160"]
        ports:
        - containerPort: 4150
          name: nsqd-tcp
          protocol: TCP
        - containerPort: 4151
          name: nsqd-http
          protocol: TCP
