apiVersion: v1
kind: Service
metadata:
  labels:
    name: nsqlookupd
  name: nsqlookupd
  namespace: db
spec:
  ports:
  - name: "nsqlookupd-tcp"
    port: 4160
    protocol: TCP
    targetPort: 4160
  - name: "nsqlookupd-http"
    port: 4161
    protocol: TCP
    targetPort: 4161
  selector:
    name: nsqlookupd
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: nsqlookupd
  name: nsqlookupd
  namespace: db
spec:
  replicas: 1
  selector:
    name: nsqlookupd
  template:
    metadata:
      labels:
        name: nsqlookupd
    spec:
      nodeSelector:
        env: DB
      containers:
      - image: node-00:30500/nsq:20151022
        name: nsqlookupd
        command: ["/nsqlookupd"]
        ports:
        - containerPort: 4160
          name: nsqlookupd-tcp
          protocol: TCP
        - containerPort: 4161
          name: nsqlookupd-http
          protocol: TCP
