---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: deepshare2-appinfo
  name: deepshare2-appinfo
  namespace: ds-production
  annotations:
    prometheus.io/scrape: 'true'
spec:
  ports:
  - name: "deepshare2"
    port: 16759
    protocol: TCP
    targetPort: 16759
  clusterIP: 10.100.1.21
  selector:
    app: deepshare2-appinfo
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: deepshare2-match
  name: deepshare2-match
  namespace: ds-production
  annotations:
    prometheus.io/scrape: 'true'
spec:
  ports:
  - name: "deepshare2"
    port: 16759
    protocol: TCP
    targetPort: 16759
  clusterIP: 10.100.1.16
  selector:
    app: deepshare2-match
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: deepshare2-cookie
  name: deepshare2-cookie
  namespace: ds-production
  annotations:
    prometheus.io/scrape: 'true'
spec:
  ports:
  - name: "deepshare2"
    port: 16759
    protocol: TCP
    targetPort: 16759
  clusterIP: 10.100.1.22
  selector:
    app: deepshare2-cookie
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: deepshare2-inappdata
  name: deepshare2-inappdata
  namespace: ds-production
  annotations:
    prometheus.io/scrape: 'true'
spec:
  ports:
  - name: "deepshare2"
    port: 16759
    protocol: TCP
    targetPort: 16759
  clusterIP: 10.100.1.23
  selector:
    app: deepshare2-inappdata
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: deepshare2-sharelink
  name: deepshare2-sharelink
  namespace: ds-production
  annotations:
    prometheus.io/scrape: 'true'
spec:
  ports:
  - name: "deepshare2"
    port: 16759
    protocol: TCP
    targetPort: 16759
  clusterIP: 10.100.1.24
  selector:
    app: deepshare2-sharelink
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: deepshare2-genurl
  name: deepshare2-genurl
  namespace: ds-production
  annotations:
    prometheus.io/scrape: 'true'
spec:
  ports:
  - name: "deepshare2"
    port: 16759
    protocol: TCP
    targetPort: 16759
  clusterIP: 10.100.1.25
  selector:
    app: deepshare2-genurl
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: deepshare2-counter
  name: deepshare2-counter
  namespace: ds-production
  annotations:
    prometheus.io/scrape: 'true'
spec:
  ports:
  - name: "deepshare2"
    port: 16759
    protocol: TCP
    targetPort: 16759
  clusterIP: 10.100.1.26
  selector:
    app: deepshare2-counter
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: deepshare2-dsaction
  name: deepshare2-dsaction
  namespace: ds-production
  annotations:
    prometheus.io/scrape: 'true'
spec:
  ports:
  - name: "deepshare2"
    port: 16759
    protocol: TCP
    targetPort: 16759
  clusterIP: 10.100.1.27
  selector:
    app: deepshare2-dsaction
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: deepshare2-bind
  name: deepshare2-bind
  namespace: ds-production
  annotations:
    prometheus.io/scrape: 'true'
spec:
  ports:
  - name: "deepshare2"
    port: 16759
    protocol: TCP
    targetPort: 16759
  clusterIP: 10.100.1.28
  selector:
    app: deepshare2-bind
