apiVersion: v1
kind: Service
metadata:
  labels:
    name: deepshare2-sharelink
  name: deepshare2-sharelink
  namespace: production
spec:
  ports:
  - name: "deepshare2"
    port: 16759
    protocol: TCP
    targetPort: 16759
  clusterIP: 10.100.1.24
  selector:
    app: deepshare2-sharelink
