apiVersion: v1
kind: ReplicationController
metadata:
  name: deployment-mysql 
  labels:
    name: deployment-mysql
  namespace:
    monitoring
spec:
  replicas: 1
  selector:
    name: deployment-mysql
  template:
    metadata:
      labels:
        name: deployment-mysql
    spec:
      nodeSelector:
        deployment: "true"
      containers:
      - resources:
          limits:
            cpu: 2
        image: r.fds.so:5000/deploy-mysql:v5.7
        name: deployment-mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            # Change this password!
            value: walle
        ports:
        - containerPort: 3306
          hostPort: 3306
          name: mysql
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-persistent-storage
      volumes:
      - name: mysql-persistent-storage
        hostPath:
          path: /opt/data/deployment/mysql/
