apiVersion: v1
kind: Service
metadata:
  labels:
    name: deployment-mysql
  name: deployment-mysql
  namespace:
    monitoring
spec:
  type:
    NodePort
  ports:
    # The port that this service should serve on.
    - port: 3306
      targetPort: 3306
      protocol: TCP
  clusterIP:
    10.100.48.97    
  # Label keys and values that must match in order to receive traffic for this service.
  selector:
    name: deployment-mysql
