---
  apiVersion: "v1"
  kind: "ReplicationController"
  metadata:
    labels:
      name: "kubedash"
      kubernetes.io/cluster-service: "true"
    name: "kubedash"
    namespace: monitoring
  spec:
    replicas: 1
    selector:
      name: "kubedash"
    template:
      metadata:
        labels:
          name: "kubedash"
          kubernetes.io/cluster-service: "true"
      spec:
        nodeSelector:
          env: monitoring
        containers:
          -
            image: "r.fds.so:5000/kubedash:v0.2.1"
            name: "kubedash"
            command:
              - "/kubedash"
              - "--headless=true"
              - "--heapster_url=http://heapster.monitoring"
            resources:
              limits:
                cpu: 50m
                memory: 100Mi
            volumeMounts:
              -
                name: "ssl-certs"
                mountPath: "/etc/ssl/certs"
                readOnly: true
        volumes:
          -
            name: "ssl-certs"
            hostPath:
              path: "/etc/ssl/certs"