apiVersion: v1
kind: Service
metadata:
  labels:
    name: nsqd-test
  name: nsqd-test
  namespace: default
spec:
  ports:
  - name: "nsqd-tcp"
    port: 4150
    protocol: TCP
    targetPort: 4150
  - name: "nsqd-http"
    port: 4151
    protocol: TCP
    targetPort: 4151
  selector:
    name: nsqd-test