apiVersion: v1
kind: ReplicationController
metadata:
  name: deepshare2-jsapi
  namespace: production
spec:
  replicas: 1
  selector:
    name: deepshare2-jsapi
  template:
    metadata:
      labels:
        name: deepshare2-jsapi
        app: deepshare2-jsapi
    spec:
      nodeSelector:
        deepshare2: "true"
      containers:
      - image: r.fds.so:5000/deepshare2-test:201603150252
        name: deepshare2-jsapi
        command: ["/go/src/github.com/MISingularity/deepshare2/deepshare2d"]
        args: ["-service-types","jsapi","-genurl-base","https://t.fds.so","-nsq-url","node-00:4150","-http-listen","0.0.0.0:16759","-match-url","10.100.1.16:16759","-cookie-url","10.100.1.22:16759","-appinfo-url","10.100.1.21:16759","-urlgenerator-url","10.100.1.25:16759","-redis-cluster-node-url","10.100.10.79:6379","-redis-pool-size","150","-log-level","info"]
        ports:
        - containerPort: 16759
          protocol: TCP
