apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-discovery
  labels:
    component: elasticsearch-logging
    role: master
  namespace: monitoring
spec:
  selector:
    component: elasticsearch-logging
    role: master
  ports:
  - name: transport
    port: 9300
    targetPort: 9300
    protocol: TCP
  type: ClusterIP