apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-logging
  labels:
    component: elasticsearch-logging
    role: client
  namespace: monitoring
spec:
  selector:
    component: elasticsearch-logging
    role: client
  ports:
  - name: http
    port: 9200
    targetPort: 9200
    protocol: TCP
  type: ClusterIP