apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: deepstats-attribution
  name: deepstats-attribution
  namespace: ds-production
spec:
  replicas: 1
  selector:
    name: deepstats-attribution
  template:
    metadata:
      labels:
        name: deepstats-attribution
    spec:
      nodeSelector:
        env: ds-production
        deepstats: "true"
      containers:
      - image: r.fds.so:5000/deepstats-attribution:201608090101
        name: deepstats-attribution
        command: ["/go/bin/deepstatsd-attribution"]
        args:
        - -nsqd-tcp-addr
        - 10.100.89.71:4150
        - -nsqlookupd-http-addr
        - 10.100.104.70:4161
        - -channel
        - deepstats_attribution
        - -mongo-addr
        - 10.100.30.61:30061,10.100.30.62:30062,10.100.30.63:30063
        - -mongocoll
        - attribution
        - -mongodb
        - deepstats
        - -topics
        - counter_raw,dsaction,inappdata
        - -redis-cluster-node-url
        - 10.100.10.11:7001,10.100.10.12:7002,10.100.10.13:7003,10.100.10.14:7004,10.100.10.15:7005,10.100.10.16:7006
        - -redis-pool-size
        - "100"
        resources:
          requests:
            memory: "2048Mi"
            cpu: "2000m"
          limits:
            memory: "2048Mi"
            cpu: "2000m"
        ports:
        - containerPort: 16759
          name: attribution
          protocol: TCP
