apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: deepstats-api
  name: deepstats-api
  namespace: ds-production
spec:
  replicas: 1
  selector:
    name: deepstats-api
  template:
    metadata:
      labels:
        name: deepstats-api
    spec:
      nodeSelector:
        env: ds-production
        deepstats: "true"
      containers:
      - image: r.fds.so:5000/deepstats-api:201608081336
        name: deepstats-api
        command: ["/go/bin/deepstats-api"]
        args:
        - -mongo-addr
        - 10.100.30.61:30061,10.100.30.62:30062,10.100.30.63:30063
        - -http-listen
        - 0.0.0.0:16759
        - -mongocoll-appchannel
        - appchannel
        - -mongocoll-appevent
        - appevent
        - -mongocoll-day-aggregate
        - day
        - -mongocoll-hour-aggregate
        - hour
        - -mongocoll-total-aggregate
        - total
        - -redis-cluster-node-url
        - 10.100.10.11:7001,10.100.10.12:7002,10.100.10.13:7003,10.100.10.14:7004,10.100.10.15:7005,10.100.10.16:7006
        - -redis-pool-size
        - "100"
        resources:
          requests:
            memory: "2048Mi"
            cpu: "2000m"
          limits:
            memory: "2048Mi"
            cpu: "2000m"
        ports:
        - containerPort: 16759
          name: api
          protocol: TCP
