apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: depstats-device
  name: deepstats-device
  namespace: ds-production
spec:
  replicas: 1
  selector:
    name: deepstats-device
  template:
    metadata:
      labels:
        name: deepstats-device
    spec:
      nodeSelector:
        env: ds-production
        deepstats: "true"
      containers:
      - image: r.fds.so:5000/deepstats-device-stats:201608090101
        name: deepstats-device
        command: ["/go/bin/deepstatsd-device"]
        args:
        - -nsqsel
        - nsqlookupd
        - -nsqd-tcp-addr
        - 10.100.89.71:4150
        - -nsqlookupd-http-addr
        - 10.100.104.70:4161
        - -channel
        - deepstats_device
        - -topics
        - counter,sharelink,dsaction,genurl,inappdata,match
        - -redis-cluster-node-url
        - 10.100.10.11:7001,10.100.10.12:7002,10.100.10.13:7003,10.100.10.14:7004,10.100.10.15:7005,10.100.10.16:7006
        - -redis-pool-size
        - "100"
        resources:
          requests:
            memory: "2048Mi"
            cpu: "2000m"
          limits:
            memory: "2048Mi"
            cpu: "2000m"
        ports:
        - containerPort: 16759
          name: device
          protocol: TCP
