apiVersion: v1
kind: Service
metadata:
  labels:
    name: mattermost-svc
  name: mattermost-svc
  namespace: kube-sys
spec:
  ports:
  - name: ""
    port: 80
    protocol: TCP
    targetPort: 80
  clusterIP: 10.100.0.65
  selector:
    name: mattermost