apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: nsqd
  name: nsqd
  namespace: ds-test
spec:
  replicas: 1
  selector:
    name: nsqd
  template:
    metadata:
      labels:
        name: nsqd
        app: nsqd
    spec:
      hostNetwork: true
      nodeSelector:
        env: ds-test
      containers:
      - image: r.fds.so:5000/nsq:20151022
        name: nsqd
        command: ["/nsqd"]
        args: ["--lookupd-tcp-address=10.100.207.1:4160"]
        ports:
        - containerPort: 4150
          hostPort: 4150
          name: nsqd-tcp
          protocol: TCP
        - containerPort: 4151
          hostPort: 4151
          name: nsqd-http
          protocol: TCP
