apiVersion: v1
kind: Service
metadata:
  labels:
    name: nsqd
  name: nsqd
  namespace: ds-test
spec:
  ports:
  - name: "nsqd-tcp"
    port: 4150
    protocol: TCP
    targetPort: 4150
  - name: "nsqd-http"
    port: 4151
    protocol: TCP
    targetPort: 4151
  selector:
    app: nsqd
