apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: 2016-04-19T09:55:44Z
  generation: 1
  labels:
    name: collect-ua
  name: collect-ua
  namespace: ds-production
  resourceVersion: "129622108"
  selfLink: /api/v1/namespaces/ds-production/replicationcontrollers/collect-ua
  uid: e2358038-0614-11e6-a8e4-0017fa001b66
spec:
  replicas: 2
  selector:
    deployment: 2d3cb58750442569e966d540fdd1ea89
    name: collect-ua
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: collect-ua
        deployment: 2d3cb58750442569e966d540fdd1ea89
        name: collect-ua
    spec:
      containers:
      - args:
        - -mongo-url
        - mongo.ds-production:27017
        command:
        - /go/src/github.com/MISingularity/deepshare2/collectua
        image: r.fds.so:5000/deepshare2-collectua:201604190946
        imagePullPolicy: IfNotPresent
        name: collect-ua
        ports:
        - containerPort: 8080
          hostPort: 8080
          name: collect-ua
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /tmp/files
          name: data
      dnsPolicy: ClusterFirst
      nodeSelector:
        env: ds-production
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /mnt/resource
        name: data
status:
  observedGeneration: 1
  replicas: 2
