apiVersion: v1
kind: Service
metadata:
  labels:
    name: collect-ua
  name: collect-ua
  namespace: ds-staging
  annotations:
    prometheus.io/scrape: 'true'
spec:
  ports:
  - name: "collect-ua"
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 31088
  type: NodePort
  selector:
    app: collect-ua
