apiVersion: v1
kind: Service
metadata:
  labels:
    name: collect-ua
  name: collect-ua
  namespace: ds-production
spec:
  ports:
  - name: "collect-ua"
    port: 8080
    protocol: TCP
    targetPort: 8080
  clusterIP: 10.100.1.20
  selector:
    app: collect-ua
