apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: chatbot
  name: chatbot
  namespace: ni-testing
spec:
  replicas: 1
  selector:
    name: chatbot
  template:
    metadata:
      labels:
        name: chatbot
    spec:
      nodeSelector:
        env: ni-testing
        chatbot: "true"
      containers:
      - image: r.fds.so:5000/chatbot-testing:201606031
        name: chatbot
        ports:
        - containerPort: 11000
          protocol: TCP
        volumeMounts:
        - mountPath: /chatbot-config
          name: chatbot-conf
      - image: r.fds.so:5000/redis
        name: redis
        command:
        - /redis-stable/src/redis-server
        - /redis-conf/redis.conf
        ports:
        - containerPort: 6379
          protocol: TCP
        volumeMounts:
        - mountPath: /redis-conf
          name: redis-conf
        - mountPath: /redis-master-data
          name: redis-data
      volumes:
      - name: chatbot-conf
        hostPath:
          path: /opt/data/ni/testing/chatbot/config
      - name: redis-conf
        hostPath:
          path: /opt/data/ni/testing/chatbot/redis/config
      - name: redis-data
        hostPath:
          path: /opt/data/ni/testing/chatbot/redis/data