apiVersion: v1
kind: Service
metadata:
  labels:
    name: mattermost
  name: mattermost
  namespace: ni-testing
spec:
  ports:
  - name: ""
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 32005
  type: NodePort
  # clusterIP: 10.100.20.65
  selector:
    name: mattermost