apiVersion: v1
kind: Service
metadata:
  labels:
    name: chatbot-clusterip
  name: chatbot-clusterip
  namespace: ni-testing
spec:
  ports:
  - name: ""
    port: 11000
    protocol: TCP
    targetPort: 11000
  clusterIP: 10.100.20.65
  selector:
    name: chatbot