apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: singularity-blog
  name: singularity-blog
  namespace: ni-production
spec:
  replicas: 2
  selector:
    name: singularity-blog
  template:
    metadata:
      labels:
        name: singularity-blog
    spec:
      nodeSelector:
        env: ni-production
        ni-blog: "true"
      containers:
      - image: r.fds.so:5000/jekyll:stable
        name: singularity-blog
        command: ["jekyll"]
        args: ["s"]
        ports:
        - containerPort: 4000
          protocol: TCP
        volumeMounts:
        - mountPath: /srv/jekyll
          name: content
      volumes:
      - name: content
        hostPath:
          path: /opt/data/ni_blog/ni_blog/ni_blog
