apiVersion: v1
kind: Service
metadata:
  labels:
    name: singularity-blog
  name: singularity-blog
  namespace: ni-production
spec:
  ports:
  - name: ""
    port: 4000
    protocol: TCP
    targetPort: 4000
  clusterIP: 10.100.30.80
  type: ClusterIP
  selector:
    name: singularity-blog
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: singularity-blog
  name: singularity-blog
  namespace: ni-staging
spec:
  ports:
  - name: ""
    port: 4000
    protocol: TCP
    targetPort: 4000
  clusterIP: 10.100.40.80
  type: ClusterIP
  selector:
    name: singularity-blog