apiVersion: v1
kind: Service
metadata:
  labels:
    name: deepstats-api
  name: deepstats-api
  namespace: ds-staging
spec:
  ports:
  - name: "api"
    port: 10002
    protocol: TCP
    targetPort: 16759
  clusterIP: 10.100.2.14
  selector:
    name: deepstats-api