apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: deepshare2-appcookie
  name: deepshare2-appcookie
  namespace: ds-staging
spec:
  replicas: 1
  selector:
    name: deepshare2-appcookie
  template:
    metadata:
      labels:
        app: deepshare2-appcookie
        name: deepshare2-appcookie
    spec:
      nodeSelector:
        env: ds-staging
      containers:
      - image: r.fds.so:5000/deepshare2-staging:201607211010
        name: deepshare2-appcookie
        command: ["/go/bin/deepshare2d"]
        args:
        - -service-types
        - appcookiedevice
        - -genurl-base
        - https://fds.so
        - -http-listen
        - 0.0.0.0:16759
        - -nsq-url
        - nsqd.ds-production:4150
        - -redis-cluster-node-url
        - 10.100.10.11:7001,10.100.10.12:7002,10.100.10.13:7003,10.100.10.14:7004,10.100.10.15:7005,10.100.10.16:7006
        - -redis-pool-size
        - "2000"
        - -log-level
        - debug
        resources:
          requests:
            memory: "1024Mi"
            cpu: "900m"
          limits:
            memory: "1024Mi"
            cpu: "900m"
        ports:
        - containerPort: 16759
          protocol: TCP
