apiVersion: v1
kind: ReplicationController
metadata:
  name: deepshare2-dsusage
  namespace: ds-staging
spec:
  replicas: 1
  selector:
    name: deepshare2-dsusage
  template:
    metadata:
      labels:
        name: deepshare2-dsusage
        app: deepshare2-dsusage
    spec:
      nodeSelector:
        env: ds-staging
      containers:
      - image:  r.fds.so:5000/deepshare2-staging:201608040802
        name: deepshare2-dsusage
        command: ["/go/bin/deepshare2d"]
        args:
        - -service-types
        - dsusage
        - -genurl-base
        - https://fds.so
        - -nsq-url
        - nsqd.ds-production:4150
        - -http-listen
        - 0.0.0.0:16759
        - -match-url
        - 10.100.2.16:16759
        - -cookie-url
        - 10.100.2.22:16759
        - -appinfo-url
        - 10.100.2.21:16759
        - -urlgenerator-url
        - 10.100.2.25:16759
        - -appcookie-url
        - 10.100.2.30:16759
        - -redis-cluster-node-url
        - 10.100.1.79:6379
        - -redis-pool-size
        - "2000"
        - -token-url
        - 10.100.2.34:16760
        - -log-level
        - debug
        resources:
          requests:
            memory: "1024Mi"
            cpu: "900m"
          limits:
            memory: "1024Mi"
            cpu: "900m"
        ports:
        - containerPort: 16759
          hostPort: 16086
          protocol: TCP
