apiVersion: v1
kind: Service
metadata:
  labels:
    name: redis3
  name: redis3
  namespace: ds-production
spec:
  ports:
  - name: "redis7000"
    port: 6379
    protocol: TCP
    targetPort: 7000
  clusterIP: 10.100.10.79
  selector:
    redis: deepshare2
