apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: deepstats-incoming
  name: deepstats-incoming
  namespace: ds-staging
spec:
  replicas: 1
  selector:
    name: deepstats-incoming
  template:
    metadata:
      labels:
        name: deepstats-incoming
    spec:
      nodeSelector:
        env: ds-staging
      containers:
      - image: r.fds.so:5000/deepstats-incoming-staging:20160421
        name: deepstats-incoming
        command: ["/go/src/github.com/MISingularity/deepshare2/deepstatsd-incoming"]
        args: ["-nsqsel","nsqlookupd","-nsqlookupd-http-addr","nsqlookupd.ds-production:4161","-mongo-addr","mongo.ds-production:27017"]
