apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: deepstats-aggregate-hour-others
  name: deepstats-aggregate-hour-others
  namespace: production
spec:
  replicas: 1
  selector:
    name: deepstats-aggregate-hour-others
  template:
    metadata:
      labels:
        name: deepstats-aggregate-hour-others
    spec:
      nodeSelector:
        deepshare2: "true"
      containers:
      - image: r.fds.so:5000/deepstats:201603311900
        name: deepstats-aggregate-hour-others
        command: ["/go/src/github.com/MISingularity/deepshare2/deepstatsd-aggregate"]
        args: ["-nsqsel","nsqlookupd","-nsqlookupd-http-addr","nsqlookupd.db:4161","-mongo-addr","mongo-deepshare2.db:27017","-agg-service","hour","-channel","deepstats_aggregate_hour","-mongocoll","hour","-mongodb","deepstats","-topics","counter,dsaction,inappdata"]
        ports:
        - containerPort: 16759
          name: aggregate-hour
          protocol: TCP
