apiVersion: v1
kind: Service
metadata:
  labels:
    name: deepshare-website
  name: deepshare-website
  namespace: ds-production
spec:
  ports:
  - name: ""
    port: 4000
    protocol: TCP
    targetPort: 4000
  clusterIP: 10.100.1.80
  type: ClusterIP
  selector:
    name: deepshare-website
