apiVersion: v1
kind: ReplicationController
metadata:
  name: cadvisor
  namespace: default
spec:
  replicas: 1
  selector:
    name: cadvisor
  template:
    metadata:
      labels:
        name: cadvisor
        app: cadvisor
    spec:
      nodeSelector:
        monitoring: "true"
      containers:
      - image: r.fds.so:5000/cadvisor:0.19.3
        name: cadvisor
        args: ["-prometheus_endpoint","/metrics","-storage_driver","influxdb","-storage_driver_db","cadvisor","-storage_driver_host","http://10.100.183.192:8086"]
        volumeMounts:
        - mountPath: /var/run
          name: docker-run-socket
        - mountPath: /rootfs
          name: root-directory
        - mountPath: /sys
          name: system-metrics
        - mountPath: /var/lib/docker
          name: docker-lib-socket
        ports:
        - containerPort: 8080
          hostPort: 28080
          protocol: TCP
      volumes:
      - hostPath: 
          path: /var/run
        name: docker-run-socket 
      - hostPath:
          path: / 
        name: root-directory
      - hostPath:
          path: /sys
        name: system-metrics
      - hostPath:
          path: /var/lib/docker
        name: docker-lib-socket
          
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: cadvisor
  name: cadvisor
  namespace: default
  annotations:
    prometheus.io/scrape: 'true'
spec:
  ports:
  - name: "cadvisor"
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 31080
  type: NodePort
  selector:
    app: cadvisor
