apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: nsqlookupd
  name: nsqlookupd
  namespace: ds-production
spec:
  replicas: 2
  selector:
    name: nsqlookupd
  template:
    metadata:
      labels:
        name: nsqlookupd
        app: nsqlookupd
    spec:
      hostNetwork: true
      nodeSelector:
        env: ds-production
        zone: deepshare
        nsqlookup: "true"
      containers:
      - image: r.fds.so:5000/nsq:20151022
        name: nsqlookupd
        command: ["/nsqlookupd"]
        ports:
        - containerPort: 4160
          hostPort: 4160
          name: nsqlookupd-tcp
          protocol: TCP
        - containerPort: 4161
          hostPort: 4161
          name: nsqlookupd-http
          protocol: TCP