apiVersion: v1
kind: Service
metadata:
  labels:
    name: nsqlookupd
  name: nsqlookupd
  namespace: ds-production
spec:
  ports:
  - name: "nsqlookupd-tcp"
    port: 4160
    protocol: TCP
    targetPort: 4160
  - name: "nsqlookupd-http"
    port: 4161
    protocol: TCP
    targetPort: 4161
  selector:
    app: nsqlookupd