---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: redis-7000
  name: redis-7000
  namespace: ds-test
spec:
  replicas: 3
  selector:
    name: redis-7000
  template:
    metadata:
      labels:
        redis: deepshare2
        name: redis-7000
    spec:
      hostNetwork: true
      nodeSelector:
        redis: "true"
      containers:
      - name: redis-7000
        image: r.fds.so:5000/redis:3.0.6
        command:
        - redis-server
        - --port 7000
        - --cluster-enabled yes
        - --cluster-config-file nodes.conf
        - --cluster-node-timeout 5000
        - --appendonly yes
        #- --dbfilename dump.rdb
        #- --dir /data
        ports:
        - containerPort: 7000
          hostPort: 7000
        - containerPort: 17000
          hostPort: 17000
        resources:
          limits:
            cpu: "0.3"
        volumeMounts:
        - mountPath: /data
          name: data-7000
      volumes:
      - name: data-7000
        hostPath:
          path: /var/lib/docker/redis-data-7000
