apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    role: nfs
  name: nfs
  namespace: ds-production
spec:
  replicas: 1
  selector:
    role: nfs
  template:
    metadata:
      labels:
        role: nfs
    spec:
      nodeSelector:
        env: ds-production
        nfs: "true"
      containers:
      - name: nfs
        image: r.fds.so:5000/nfs
        ports:
          - name: nfs
            containerPort: 2049
        resources:
            limits:
              cpu: "0.1"
        volumeMounts:
        - mountPath: /exports
          name: data
        securityContext:
          privileged: true
      volumes:
      - hostPath:
          path: /var/lib/docker/nfs
        name: data
---
kind: Service
apiVersion: v1
metadata:
  name: nfs
  namespace: ds-production
spec:
  ports:
    - port: 2049
  clusterIP: 10.100.0.98
  selector:
    role: nfs