name: k8s1-1-1
nodes:
  master: 5
  node: 4
weave_salt: 19aa62121d36acdbd0f4cfda615ef3c4f8d20b2a721d2e39cb4ae99d5adad0ab
resources:
  vnet: vnet-kubernetes-test
  service: k8s1-1-1-14a7d6d61adb78
  ssh_key:
    key: ./output/k8s1-1-1_14a7d6d61adb78_ssh.key
    pem: ./output/k8s1-1-1_14a7d6d61adb78_ssh.pem
  storage_account: deepshare2
hosts:
  - name: master-00
    port: 2201
    cloud_config_file: ./output/master_14a7d6d61adb78_generated.yml
  - name: master-01
    port: 2202
    cloud_config_file: ./output/master_14a7d6d61adb78_generated.yml
  - name: master-02
    port: 2203
    cloud_config_file: ./output/master_14a7d6d61adb78_generated.yml
  - name: master-03
    port: 2204
    cloud_config_file: ./output/master_14a7d6d61adb78_generated.yml
  - name: master-04
    port: 2205
    cloud_config_file: ./output/master_14a7d6d61adb78_generated.yml
  - name: node-00
    port: 2206
    cloud_config_file: ./output/node_14a7d6d61adb78_generated.yml
  - name: node-01
    port: 2207
    cloud_config_file: ./output/node_14a7d6d61adb78_generated.yml
  - name: node-02
    port: 2208
    cloud_config_file: ./output/node_14a7d6d61adb78_generated.yml
  - name: node-03
    port: 2209
    cloud_config_file: ./output/node_14a7d6d61adb78_generated.yml
