name: k8s1-1-1
nodes:
  master: 5
  node: 0
weave_salt: 192d1702a8d1d41cef51476468b558181161fd0eb41d31980ea8d0d797bef5d6
resources:
  vnet: vnet-kubernetes-test
  service: k8s1-1-1-79e1c6b10a69d9
  ssh_key:
    key: ./output/k8s1-1-1_79e1c6b10a69d9_ssh.key
    pem: ./output/k8s1-1-1_79e1c6b10a69d9_ssh.pem
  storage_account: deepshare2
hosts:
  - name: master-00
    port: 2201
    cloud_config_file: ./output/master_79e1c6b10a69d9_generated.yml
  - name: master-01
    port: 2202
    cloud_config_file: ./output/master_79e1c6b10a69d9_generated.yml
  - name: master-02
    port: 2203
    cloud_config_file: ./output/master_79e1c6b10a69d9_generated.yml
  - name: master-03
    port: 2204
    cloud_config_file: ./output/master_79e1c6b10a69d9_generated.yml
  - name: master-04
    port: 2205
    cloud_config_file: ./output/master_79e1c6b10a69d9_generated.yml
