name: k8s1-1-1
nodes:
  master: 5
  node: 0
weave_salt: 6ad9b6f3e3b53aef818cec1ec2deea05d8d6e7ff0a0d691873f02e09042a55ee
resources:
  vnet: vnet-kubernetes-test
  service: k8s1-1-1-b04f350fac2aaf
  ssh_key:
    key: ./output/k8s1-1-1_b04f350fac2aaf_ssh.key
    pem: ./output/k8s1-1-1_b04f350fac2aaf_ssh.pem
  storage_account: deepshare2
hosts:
  - name: master-00
    port: 2201
    cloud_config_file: ./output/master_b04f350fac2aaf_generated.yml
  - name: master-01
    port: 2202
    cloud_config_file: ./output/master_b04f350fac2aaf_generated.yml
  - name: master-02
    port: 2203
    cloud_config_file: ./output/master_b04f350fac2aaf_generated.yml
  - name: master-03
    port: 2204
    cloud_config_file: ./output/master_b04f350fac2aaf_generated.yml
  - name: master-04
    port: 2205
    cloud_config_file: ./output/master_b04f350fac2aaf_generated.yml
