apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: db-backup
  name: db-bakcup
  namespace: monitoring
spec:
  replicas: 1
  selector:
    name: db-backup
  template:
    metadata:
      labels:
        app: db-backup
        name: db-backup
    spec:
      nodeSelector:
        env: monitoring
        backup: "true"
      containers:
      - image: r.fds.so:5000/backup3
        name: db-backup
        command:
          - "/usr/bin/start-cron.sh"
