apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: singularity-website
  name: singularity-website
  namespace: ni-staging
spec:
  replicas: 2
  selector:
    name: singularity-website
  template:
    metadata:
      labels:
        name: singularity-website
    spec:
      nodeSelector:
        env: ni-production
        ni-website: "true"
      containers:
      - image: r.fds.so:5000/jekyll:stable
        name: singularity-website
        command: ["jekyll"]
        args: ["s"]
        ports:
        - containerPort: 4000
          protocol: TCP
        volumeMounts:
        - mountPath: /srv/jekyll
          name: content
      volumes:
      - name: content
        hostPath:
          path: /opt/data/ni_website/ni_website_staging/ni_website
