apiVersion: v1
kind: ReplicationController
metadata:
  name: deepshare-proxy-jumei
  namespace: ds-test
spec:
  replicas: 1
  selector:
    name: deepshare-proxy-jumei
  template:
    metadata:
      labels:
        name: deepshare-proxy-jumei
    spec:
      nodeSelector:
        env: ds-test
      containers:
      - image: r.fds.so:5000/jumei-nginx:20160711
        name: deepshare-proxy
        ports:
        - containerPort: 443
          hostPort: 10443
          protocol: TCP
        - containerPort: 80
          hostPort: 10080
          protocol: TCP
        volumeMounts:
        - mountPath: /apple-app-site
          name: apple-app-site
      volumes:
      - name: apple-app-site
        hostPath:
          path: /opt/datastaging/ds/apple-app-site
