apiVersion: v1
kind: ReplicationController
metadata:
  name: deepshare-io-proxy
  namespace: ds-production
spec:
  replicas: 2
  selector:
    name: deepshare-io-proxy
  template:
    metadata:
      labels:
        name: deepshare-io-proxy
    spec:
      nodeSelector:
        env: ds-production
        zone: deepshare-io
      containers:
      - image: r.fds.so:5000/ds-nginx:2016081601
        name: deepshare-proxy
        resources:
          requests:
            memory: "4096Mi"
            cpu: "2000m"
          limits:
            memory: "4096Mi"
            cpu: "2000m"
        ports:
        - containerPort: 443
          hostPort: 32101
          protocol: TCP
        - containerPort: 80
          hostPort: 32102
          protocol: TCP
        volumeMounts:
        - mountPath: /apple-app-site
          name: apple-app-site
      volumes:
      - name: apple-app-site
        hostPath:
          path: /opt/data/ds/apple-app-site
