apiVersion: v1
kind: ReplicationController
metadata:
  name: kube-prometheus-alertmanager
  namespace: monitoring
spec:
  replicas: 1
  selector:
    name: kube-prometheus-alertmanager
  template:
    metadata:
      labels:
        name: kube-prometheus-alertmanager
    spec:
      nodeSelector:
        env: monitoring 
        alertmanager: "true"
      containers:
      - image: r.fds.so:5000/alertmanager-sms1
        name: alertmanager
        env:
          - name: SMTP_AUTH_USERNAME
            value: mingfeng.zhang@misingularity.com
          - name: SMTP_AUTH_PASSWORD
            value: zhang123
        args: ["-config.file","/alertmanager/alertmanager.conf","-log.format","logger:stdout?json=true","-log.level","debug"]
        ports:
        - containerPort: 9093
          hostPort: 9093
          protocol: TCP
        volumeMounts:
          - mountPath: /alertmanager
            name: prometheus
      volumes:
        - name: prometheus
          hostPath:
            path: /var/lib/docker/nfs/data/



