apiVersion: v1
kind: ReplicationController
metadata:
  name: prometheus-node-exporter
  namespace: monitoring
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: node-exporter
      name: node-exporter
    spec:
      nodeSelector:
        nginx: "true"
      containers:
      - image: r.fds.so:5000/nginx_exporter:v1
        name: node-exporter
        command:
          - "/bin/nginx_exporter"
        args: ["-nginx.scrape_uri",""]
        ports:
        - containerPort: 9113
          hostPort: 9113
          name: scrape
      hostNetwork: true
      hostPID: true
