apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  namespace: monitoring
  labels:
    app: node-exporter
    name: node-exporter
  name: node-exporter
spec:
  clusterIP: 10.100.48.95
  ports:
  - name: scrape
    port: 9100
    protocol: TCP
  selector:
    app: node-exporter
  type: ClusterIP
