apiVersion: v1
kind: ReplicationController
metadata:
  name: prometheus-nsq
  namespace: monitoring
spec:
  replicas: 1
  selector:
    name: prometheus-nsq-exporter
  template:
    metadata:
      labels:
        name: prometheus-nsq-exporter
    spec:
      nodeSelector:
        env: monitoring
      containers:
      - image: r.fds.so:5000/nsq-exporter:v1
        name: nsq-exporter
        command:
          - "/bin/nsq_exporter"
        args: ["-nsqd.addr","10.100.89.71:4151/stats"]
        ports:
        - containerPort: 9117
          hostPort: 9117
          protocol: TCP



