apiVersion: v1
kind: Service
metadata:
  labels:
    name: deepshare2-match
  name: deepshare2-match
  namespace: ds-production
  annotations:
    prometheus.io/scrape: 'true'
spec:
  ports:
  - name: "deepshare2"
    port: 16759
    protocol: TCP
    targetPort: 16759
  clusterIP: 10.100.1.16
  selector:
    app: deepshare2-match
