apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: deepshare-proxy-jumeiyoupin
  name: deepshare-proxy-jumeiyoupin
  namespace: ds-kehu
spec:
  replicas: 3
  selector:
    name: deepshare-proxy-jumeiyoupin
  template:
    metadata:
      labels:
        name: deepshare-proxy-jumeiyoupin
    spec:
      containers:
      - image: r.fds.so:5000/jumei-nginx:2016072101
        name: deepshare-proxy-jumeiyoupin
        ports:
        - containerPort: 443
          hostPort: 10443
          protocol: TCP
        - containerPort: 80
          hostPort: 10080
          protocol: TCP
        volumeMounts:
        - mountPath: /apple-app-site
          name: apple-app-site
      nodeSelector:
        kehu: "true"
        jumei: "true"
      volumes:
      - hostPath:
          path: /opt/data/ds/apple-app-site
        name: apple-app-site
