kind: PersistentVolume
apiVersion: v1
metadata:
  name: deepshare-website-ds-staging
  labels:
    name: deepshare-website-ds-staging
spec:
  capacity:
    storage: 800Mi
  accessModes:
    - ReadWriteMany
  nfs:
    path: "/deepshare_website-staging"
    server: 10.100.0.98
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: deepshare-website
  namespace: ds-staging
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 800Mi