apiVersion: v1
kind: ReplicationController
metadata:
  name: el
  labels:
    name: elasticsearch
  namespace: ni-testing
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: elasticsearch
    spec:
      nodeSelector:
        env: ni-testing
        elasticsearch: "true"
      containers:
      - name: elasticsearch
        image: r.fds.so:5000/docker-elasticsearch23:20160527
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: storage
      volumes:
      - name: storage
        hostPath:
          path: /opt/data/ni/testing/elasticsearch
