apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: ni-testing
spec:
  type: ClusterIP
  selector:
    name: elasticsearch
  ports:
  - name: http
    port: 9200
    protocol: TCP
  clusterIP: 10.100.10.92