apiVersion: v1
kind: ReplicationController
metadata:
  name: deepshare-proxy-rolling
  namespace: ds-production
spec:
  replicas: 2
  selector:
    name: deepshare-proxy-rolling
  template:
    metadata:
      labels:
        name: deepshare-proxy-rolling
    spec:
      nodeSelector:
        env: ds-production
        zone: nginx
      containers:
      - image: r.fds.so:5000/fds-nginx:2016082801
        name: deepshare-proxy
        ports:
        - containerPort: 443
          hostPort: 10443
          protocol: TCP
        - containerPort: 80
          hostPort: 10080
          protocol: TCP
        resources:
          requests:
            memory: "4096Mi"
            cpu: "2000m"
          limits:
            memory: "4096Mi"
            cpu: "2000m"
        volumeMounts:
        - mountPath: /apple-app-site
          name: apple-app-site
        - mountPath: /writableproc
          name: proc
      volumes:
      - hostPath:
          path: /opt/data/ds/apple-app-site
        name: apple-app-site
      - hostPath:
          path: /proc
        name: proc
