---
apiVersion: v1
kind: Service
metadata:
  name: mongo-shard2-30011
  namespace: ds-db
  labels:
    name: mongo-shard2-30011
spec:
  ports:
  - name: mongo-shard2-30011
    port: 30011
    protocol: TCP
    targetPort: 30011
  clusterIP: 10.100.30.11
  selector:
    app: mongo-shard2-30011
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-shard2-30012
  namespace: ds-db
  labels:
    name: mongo-shard2-30012
spec:
  ports:
  - name: mongo-shard2-30012
    port: 30012
    protocol: TCP
    targetPort: 30012
  clusterIP: 10.100.30.12
  selector:
    app: mongo-shard2-30012
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-shard2-30013
  namespace: ds-db
  labels:
    name: mongo-shard2-30013
spec:
  ports:
  - name: mongo-shard2-30013
    port: 30013
    protocol: TCP
    targetPort: 30013
  clusterIP: 10.100.30.13
  selector:
    app: mongo-shard2-30013
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: mongo-shard2-30011
  namespace: ds-db
  labels:
    app: mongo-shard2-30011
spec:
  replicas: 1
  selector:
    app: mongo-shard2-30011
  template:
    metadata:
      name: mongo-shard2-30011
      labels:
        app: mongo-shard2-30011
    spec:
      hostNetwork: true
      nodeSelector:
        mongo: "true"
        shard2: "30011"
      containers:
      - image: r.fds.so:5000/mongo:3.2.8
        name: mongo-shard2-30011
        command:
        - mongod
        - --storageEngine
        - "wiredTiger"
        - --wiredTigerCacheSizeGB
        - "1"
        - --port
        - "30011"
        - --dbpath=/data/mongo
        - --directoryperdb
        - --replSet
        - "shard2"
        - --shardsvr
        - --oplogSize
        - "1024"
        resources:
          requests:
            memory: "2048Mi"
            cpu: "1000m"
          limits:
            memory: "2048Mi"
            cpu: "1000m"
        ports:
        - name: mongo-30011
          containerPort: 30011
          protocol: TCP
          hostPort: 30011
        volumeMounts:
        - name: mongo-data
          mountPath: /data/mongo
      volumes:
      - name: mongo-data
        hostPath:
          path: /mnt/data/mongo/30011
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: mongo-shard2-30012
  namespace: ds-db
  labels:
    app: mongo-shard2-30012
spec:
  replicas: 1
  selector:
    app: mongo-shard2-30012
  template:
    metadata:
      name: mongo-shard2-30012
      labels:
        app: mongo-shard2-30012
    spec:
      hostNetwork: true
      nodeSelector:
        mongo: "true"
        shard2: "30012"
      containers:
      - image: r.fds.so:5000/mongo:3.2.8
        name: mongo-shard2-30012
        command:
        - mongod
        - --storageEngine
        - "wiredTiger"
        - --wiredTigerCacheSizeGB
        - "1"
        - --port
        - "30012"
        - --dbpath=/data/mongo
        - --directoryperdb
        - --replSet
        - "shard2"
        - --shardsvr
        - --oplogSize
        - "1024"
        resources:
          requests:
            memory: "2048Mi"
            cpu: "1000m"
          limits:
            memory: "2048Mi"
            cpu: "1000m"
        ports:
        - name: mongo-30012
          containerPort: 30012
          protocol: TCP
          hostPort: 30012
        volumeMounts:
        - name: mongo-data
          mountPath: /data/mongo
      volumes:
      - name: mongo-data
        hostPath:
          path: /mnt/data/mongo/30012
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: mongo-shard2-30013
  namespace: ds-db
  labels:
    app: mongo-shard2-30013
spec:
  replicas: 1
  selector:
    app: mongo-shard2-30013
  template:
    metadata:
      name: mongo-shard2-30013
      labels:
        app: mongo-shard2-30013
    spec:
      hostNetwork: true
      nodeSelector:
        mongo: "true"
        shard2: "30013"
      containers:
      - image: r.fds.so:5000/mongo:3.2.8
        name: mongo-shard2-30013
        command:
        - mongod
        - --storageEngine
        - "wiredTiger"
        - --wiredTigerCacheSizeGB
        - "1"
        - --port
        - "30013"
        - --dbpath=/data/mongo
        - --directoryperdb
        - --replSet
        - "shard2"
        - --shardsvr
        - --oplogSize
        - "1024"
        resources:
          requests:
            memory: "2048Mi"
            cpu: "1000m"
          limits:
            memory: "2048Mi"
            cpu: "1000m"
        ports:
        - name: mongo-30013
          containerPort: 30013
          protocol: TCP
          hostPort: 30013
        volumeMounts:
        - name: mongo-data
          mountPath: /data/mongo
      volumes:
      - name: mongo-data
        hostPath:
          path: /mnt/data/mongo/30013
