---
apiVersion: v1
kind: Service
metadata:
  name: mongo-shard1-30001
  namespace: ds-db
  labels:
    name: mongo-shard1-30001
spec:
  ports:
  - name: mongo-shard1-30001
    port: 30001
    protocol: TCP
    targetPort: 30001
  clusterIP: 10.100.30.1
  selector:
    app: mongo-shard1-30001
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-shard1-30002
  namespace: ds-db
  labels:
    name: mongo-shard1-30002
spec:
  ports:
  - name: mongo-shard1-30002
    port: 30002
    protocol: TCP
    targetPort: 30002
  clusterIP: 10.100.30.2
  selector:
    app: mongo-shard1-30002
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-shard1-30003
  namespace: ds-db
  labels:
    name: mongo-shard1-30003
spec:
  ports:
  - name: mongo-shard1-30003
    port: 30003
    protocol: TCP
    targetPort: 30003
  clusterIP: 10.100.30.3
  selector:
    app: mongo-shard1-30003
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: mongo-shard1-30001
  namespace: ds-db
  labels:
    app: mongo-shard1-30001
spec:
  replicas: 1
  selector:
    app: mongo-shard1-30001
  template:
    metadata:
      name: mongo-shard1-30001
      labels:
        app: mongo-shard1-30001
    spec:
      hostNetwork: true
      nodeSelector:
        mongo: "true"
        shard1: "30001"
      containers:
      - image: r.fds.so:5000/mongo:3.2.8
        name: mongo-shard1-30001
        command:
        - mongod
        - --storageEngine
        - "wiredTiger"
        - --wiredTigerCacheSizeGB
        - "1"
        - --port
        - "30001"
        - --dbpath=/data/mongo
        - --directoryperdb
        - --replSet
        - "shard1"
        - --shardsvr
        - --oplogSize
        - "1024"
        resources:
          requests:
            memory: "2048Mi"
            cpu: "1000m"
          limits:
            memory: "2048Mi"
            cpu: "1000m"
        ports:
        - name: mongo-30001
          containerPort: 30001
          protocol: TCP
          hostPort: 30001
        volumeMounts:
        - name: mongo-data
          mountPath: /data/mongo
      volumes:
      - name: mongo-data
        hostPath:
          path: /mnt/data/mongo/30001
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: mongo-shard1-30002
  namespace: ds-db
  labels:
    app: mongo-shard1-30002
spec:
  replicas: 1
  selector:
    app: mongo-shard1-30002
  template:
    metadata:
      name: mongo-shard1-30002
      labels:
        app: mongo-shard1-30002
    spec:
      hostNetwork: true
      nodeSelector:
        mongo: "true"
        shard1: "30002"
      containers:
      - image: r.fds.so:5000/mongo:3.2.8
        name: mongo-shard1-30002
        command:
        - mongod
        - --storageEngine
        - "wiredTiger"
        - --wiredTigerCacheSizeGB
        - "1"
        - --port
        - "30002"
        - --dbpath=/data/mongo
        - --directoryperdb
        - --replSet
        - "shard1"
        - --shardsvr
        - --oplogSize
        - "1024"
        resources:
          requests:
            memory: "2048Mi"
            cpu: "1000m"
          limits:
            memory: "2048Mi"
            cpu: "1000m"
        ports:
        - name: mongo-30002
          containerPort: 30002
          protocol: TCP
          hostPort: 30002
        volumeMounts:
        - name: mongo-data
          mountPath: /data/mongo
      volumes:
      - name: mongo-data
        hostPath:
          path: /mnt/data/mongo/30002
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: mongo-shard1-30003
  namespace: ds-db
  labels:
    app: mongo-shard1-30003
spec:
  replicas: 1
  selector:
    app: mongo-shard1-30003
  template:
    metadata:
      name: mongo-shard1-30003
      labels:
        app: mongo-shard1-30003
    spec:
      hostNetwork: true
      nodeSelector:
        mongo: "true"
        shard1: "30003"
      containers:
      - image: r.fds.so:5000/mongo:3.2.8
        name: mongo-shard1-30003
        command:
        - mongod
        - --storageEngine
        - "wiredTiger"
        - --wiredTigerCacheSizeGB
        - "1"
        - --port
        - "30003"
        - --dbpath=/data/mongo
        - --directoryperdb
        - --replSet
        - "shard1"
        - --shardsvr
        - --oplogSize
        - "1024"
        resources:
          requests:
            memory: "2048Mi"
            cpu: "1000m"
          limits:
            memory: "2048Mi"
            cpu: "1000m"
        ports:
        - name: mongo-30003
          containerPort: 30003
          protocol: TCP
          hostPort: 30003
        volumeMounts:
        - name: mongo-data
          mountPath: /data/mongo
      volumes:
      - name: mongo-data
        hostPath:
          path: /mnt/data/mongo/30003
