apiVersion: v1
kind: Service
metadata:
  labels:
    name: deepshare2-snowflake
  name: deepshare2-snowflake
  namespace: ds-staging
  annotations:
    prometheus.io/scrape: 'true'
spec:
  ports:
  - name: "deepshare2-snowflake"
    port: 16760
    protocol: TCP
    nodePort: 31760
  type: NodePort
  clusterIP: 10.100.2.34
  selector:
    app: deepshare2-snowflake
