apiVersion: v1
kind: Service
metadata:
  labels:
    name: deepshare2-jsapi
  name: deepshare2-jsapi
  namespace: ds-staging
  annotations:
    prometheus.io/scrape: 'true'
spec:
  ports:
  - name: "deepshare2"
    port: 16759
    protocol: TCP
    targetPort: 16759
  clusterIP: 10.100.2.33
  selector:
    app: deepshare2-jsapi
