apiVersion: v1
kind: Service
metadata:
  labels:
    name: qd-registry
  name: qd-registry
  namespace: kube-sys
spec:
  ports:
  - name: "web"
    port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 30500
  clusterIP: 10.100.0.50
  type: NodePort
  selector:
    name: qd-registry2-2-1