apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: nsqd
  name: nsqd
  namespace: ds-production
spec:
  replicas: 2
  selector:
    name: nsqd
  template:
    metadata:
      labels:
        name: nsqd
        app: nsqd
    spec:
      hostNetwork: true
      nodeSelector:
        env: ds-production
        # nsq: "true"
        zone: deepshare
      containers:
      - image: r.fds.so:5000/nsq:20151022
        name: nsqd
        command: ["/nsqd"]
        args: ["--lookupd-tcp-address=172.16.0.12:4160,172.16.0.13:4160"]
        ports:
        - containerPort: 4150
          hostPort: 4150
          name: nsqd-tcp
          protocol: TCP
        - containerPort: 4151
          hostPort: 4151
          name: nsqd-http
          protocol: TCP
