apiVersion: v1
kind: ReplicationController
metadata:
  name: redis
  namespace: db
spec:
  replicas: 1
  selector:
    name: redis
  template:
    metadata:
      labels:
        name: redis
    spec:
      nodeSelector:
        env: DB
      containers:
      - name: redis
        image: node-00:30500/redis:cluster-v1
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: "0.5"
        volumeMounts:
        - mountPath: /data
          name: data
      volumes:
        - name: data
          emptyDir: {}
