apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: redis-deepshare1
  name: redis-deepshare1
  namespace: db
spec:
  replicas: 1
  selector:
    name: redis-deepshare1
  template:
    metadata:
      labels:
        name: redis-deepshare1
    spec:
      nodeSelector:
        env: DB
      containers:
      - image: node-00:30500/redis
        name: redis-deepshare1
        command:
        - /redis-stable/src/redis-server
        - /redis-conf/redis.conf
        ports:
        - containerPort: 6379
          protocol: TCP
        volumeMounts:
        - mountPath: /redis-conf
          name: redis-conf
        - mountPath: /redis-master-data
          name: redis-data
      volumes:
      - name: redis-conf
        persistentVolumeClaim:
          claimName: redis-deepshare1-conf
      - name: redis-data
        persistentVolumeClaim:
          claimName: redis-deepshare1-dump
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: redis-deepshare1
  name: redis-deepshare1
  namespace: db
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    name: redis-deepshare1

