apiVersion: v1
kind: Service
metadata:
  labels:
    name: redis
  name: redis
  namespace: db
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  clusterIP: 10.100.1.79
  selector:
    name: redis