apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: db
  name: codis-proxy
  namespace: db
spec:
  replicas: 1
  selector:
    name: codis-proxy
  template:
    metadata:
      labels:
        name: codis-proxy
    spec:
      nodeSelector:
        env: DB
      containers:
      - image: node-00:30500/codis-proxy
        name: codis-proxy
        ports:
        - name: "port1"
          containerPort: 19000
          protocol: TCP
        - name: "port2"
          containerPort: 11000
          protocol: TCP
        resources:
          limits:
            cpu: "1"
        volumeMounts:
        - mountPath: /etc/codis/conf/codis-proxy
          name: codis-proxy
        - mountPath: /log
          name: proxy-log
      volumes:
      - name: codis-proxy
        persistentVolumeClaim:
          claimName: codis-conf
      - name: proxy-log
        hostPath:
          path: /mnt/resource/proxy-log