apiVersion: v1
kind: Service
metadata:
  labels:
    name: codis-proxy
  name: codis-proxy
  namespace: db
spec:
  ports:
  - name: "port1"
    port: 6379
    protocol: TCP
    targetPort: 19000
  - name: "port2"
    port: 6380
    protocol: TCP
    targetPort: 11000
  clusterIP: 10.100.0.79
  selector:
    name: codis-proxy