apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: codis-redis-6380
  name: codis-redis-6380
  namespace: db
spec:
  replicas: 1
  selector:
    name: codis-redis-6380
  template:
    metadata:
      labels:
        name: codis-redis-6380
    spec:
      nodeSelector:
        env: DB
      containers:
      - name: codis-redis-6380
        image: node-00:30500/codis-server
        ports:
        - containerPort: 6379
          hostPort: 16380
        resources:
          limits:
            cpu: "0.3"
        volumeMounts:
        - mountPath: /etc/codis/conf/redis-master
          name: conf-6380
        - mountPath: /redis-master-data
          name: data-6380
      volumes:
      - name: conf-6380
        persistentVolumeClaim:
          claimName: codis-conf
      - name: data-6380
        hostPath:
          path: /mnt/resources/redis-data-6380
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: codis-redis-6381
  name: codis-redis-6381
  namespace: db
spec:
  replicas: 1
  selector:
    name: codis-redis-6381
  template:
    metadata:
      labels:
        name: codis-redis-6381
    spec:
      nodeSelector:
        env: DB
      containers:
      - name: codis-redis-6381
        image: node-00:30500/codis-server
        ports:
        - containerPort: 6379
          hostPort: 16381
        resources:
          limits:
            cpu: "0.3"
        volumeMounts:
        - mountPath: /etc/codis/conf/redis-master
          name: conf-6381
        - mountPath: /redis-master-data
          name: data-6381
      volumes:
      - name: conf-6381
        persistentVolumeClaim:
          claimName: codis-conf
      - name: data-6381
        hostPath:
          path: /mnt/resources/redis-data-6381
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: codis-redis-6382
  name: codis-redis-6382
  namespace: db
spec:
  replicas: 1
  selector:
    name: codis-redis-6382
  template:
    metadata:
      labels:
        name: codis-redis-6382
    spec:
      nodeSelector:
        env: DB
      containers:
      - name: codis-redis-6382
        image: node-00:30500/codis-server
        ports:
        - containerPort: 6379
          hostPort: 16382
        resources:
          limits:
            cpu: "0.3"
        volumeMounts:
        - mountPath: /etc/codis/conf/redis-master
          name: conf-6382
        - mountPath: /redis-master-data
          name: data-6382
      volumes:
      - name: conf-6382
        persistentVolumeClaim:
          claimName: codis-conf
      - name: data-6382
        hostPath:
          path: /mnt/resources/redis-data-6382
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: codis-redis-6383
  name: codis-redis-6383
  namespace: db
spec:
  replicas: 1
  selector:
    name: codis-redis-6383
  template:
    metadata:
      labels:
        name: codis-redis-6383
    spec:
      nodeSelector:
        env: DB
      containers:
      - name: codis-redis-6383
        image: node-00:30500/codis-server
        ports:
        - containerPort: 6379
          hostPort: 16383
        resources:
          limits:
            cpu: "0.3"
        volumeMounts:
        - mountPath: /etc/codis/conf/redis-master
          name: conf-6383
        - mountPath: /redis-master-data
          name: data-6383
      volumes:
      - name: conf-6383
        persistentVolumeClaim:
          claimName: codis-conf
      - name: data-6383
        hostPath:
          path: /mnt/resources/redis-data-6383